Reworking of bindgen wrapper logic

diff --git a/tools/bindgen/bindgen-macosx b/tools/bindgen/bindgen-macosx
--- a/tools/bindgen/bindgen-macosx
+++ b/tools/bindgen/bindgen-macosx
@@ -7,4 +7,16 @@ set -e
 set -u
 set -f
 
-DYLD_LIBRARY_PATH=/usr/local/opt/llvm/lib CLANG_PATH=/usr/local/opt/llvm/bin/clang exec bindgen "$@"
+if ! command -v brew 1>/dev/null 2>/dev/null; then
+	printf '%s\n' "Could not locate Homebrew brew in PATH" 1>&2
+	exit 1
+fi
+
+if ! command -v bindgen 1>/dev/null 2>/dev/null; then
+	printf '%s\n' "Could not locate bindgen in PATH" 1>&2
+	exit 1
+fi
+
+prefix="$(brew --prefix)"
+llvmPrefix="$prefix"/opt/llvm
+DYLD_LIBRARY_PATH="$llvmPrefix"/lib CLANG_PATH="$llvmPrefix"/bin/clang exec bindgen "$@"
